import z from "zod";

export const ATHLETE_METADATA = {
    ASSOCIATION_LEVELS: "associationLevel",
    SPORT: "sport",
    AGENCY: "agency",
    PERSONALITY_TRAIT: "personalityTrait",
    GENDER: "gender",
    NCCS: "nccs",
    KEY_MARKETS: "keyMarket",
    TERTIARY: "tertiary",
    STATE: "state",
    NATIONALITY: "nationality",
    SOCIAL_MEDIA: "socialMedia",
    ATHLETE_STATUS: "athleteStatus",
} as const;

export const athleteFormSchema = z.object({
    name: z.string().min(1, "Required"),
    associationLevelId: z.string().optional(),
    costOfAssociation: z.string().optional(),
    userId: z.string().min(1, "Required"),
    sportId: z.string().optional(),
    agencyId: z.string().optional(),
    age: z.string().optional(),
    facebook: z.string().optional(),
    instagram: z.string().optional(),
    twitter: z.string().optional(),
    linkedin: z.string().optional(),
    youtube: z.string().optional(),
    website: z.string().optional(),
    subPersonalityTraitIds: z.string().array().optional(),
    genderId: z.string().optional(),
    nccsIds: z.string().array().optional(),
    primaryMarketIds: z.string().array().optional(),
    secondaryMarketIds: z.string().array().optional(),
    tertiaryIds: z.string().array().optional(),
    stateId: z.string().optional(),
    nationalityId: z.string().optional(),
    primarySocialMediaPlatformIds: z.string().array().optional(),
    secondarySocialMediaPlatformIds: z.string().array().optional(),
    statusId: z.string().optional(),
    contactName: z.string().optional(),
    contactDesignation: z.string().optional(),
    contactEmail: z.string().optional(),
    contactNumber: z.string().optional(),
    contactLinkedin: z.string().optional(),
});

export type TAthleteFormSchema = z.infer<typeof athleteFormSchema>;
