import z from "zod";

export const BRAND_METADATA = {
    PARENT_ORG: "parentOrg",
    CATEGORY: "category",
    CITY: "city",
    STATE: "state",
    AGENCY: "agency",
    TIER: "tier",
    PERSONALITY_TRAIT: "personalityTrait",
    TAGLINE: "tagline",
    NCCS: "nccs",
    MARKETING_PLATFORM: "marketingPlatform",
    AGE: "age",
    GENDER: "gender",
    TERTIARY: "tertiary",
    ACTIVE_CAMPAIGN: "activeCampaign",
    KEY_MARKETS: "keyMarket",
} as const;

export const brandFormSchema = z.object({
    name: z.string(),
    userId: z.string(),
    parentOrgId: z.string().optional(),
    subCategoryIds: z.string().array().optional(),
    cityId: z.string().optional(),
    stateId: z.string().optional(),
    agencyId: z.string().optional(),
    tierIds: z.string().array().optional(),
    instagram: z.string().optional(),
    facebook: z.string().optional(),
    linkedin: z.string().optional(),
    twitter: z.string().optional(),
    youtube: z.string().optional(),
    website: z.string().optional(),
    subPersonalityTraitIds: z.string().array().optional(),
    strategyOverview: z.string().optional(),
    taglineIds: z.string().array().optional(),
    activeCampaignIds: z.string().array().optional(),
    primaryMarketIds: z.string().array().optional(),
    secondaryMarketIds: z.string().array().optional(),
    tertiaryIds: z.string().array().optional(),
    nccsIds: z.string().array().optional(),
    primaryMarketingPlatformIds: z.string().array().optional(),
    secondaryMarketingPlatformIds: z.string().array().optional(),
    ageIds: z.string().array().optional(),
    genderIds: z.string().array().optional(),
    contactName: z.string().optional(),
    contactDesignation: z.string().optional(),
    contactEmail: z.string().optional(),
    contactNumber: z.string().optional(),
    contactLinkedin: z.string().optional(),
});

export type TBrandFormSchema = z.infer<typeof brandFormSchema>;
