export const TEAM_METADATA = {
    SPORT: "sports",
    LEAGUE: "leagues",
    LEAGUE_OWNER: "leagueOwners",
    CITY: "cities",
    STATE: "states",
    PERSONALITY_TRAIT: "personalityTraits",
    TIER: "tiers",
    TAGLINE: "taglines",
    ACTIVE_CAMPAIGN: "activeCampaigns",
    MARKETING_PLATFORM: "marketingPlatforms",
    AGE: "ageRanges",
    GENDER: "genders",
    NCCS: "nccsList",
    KEY_MARKETS: "keyMarkets",
    TERTIARY: "tertiaries",
    ASSET: "assets",
    ASSOCIATION_LEVEL: "associationLevels",
} as const;
